services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT}:5433"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: